services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: instagram-post-classifier-api
    ports:
      - "8000:8000"
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app